Update Travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,25 +1,48 @@
 language: python
 python:
-  - "3.6"
-
-install:
-  - pip install --only-binary=numpy,scipy,pandas numpy scipy pandas pytest pytest-cov codecov --quiet
-  
-  # install TensorFlow (CPU version).
-  - pip install tensorflow==1.12.0 --quiet
-  
-  # install PyTorch (CPU version).
-  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl --quiet
-  
-  # install other setup extensions.
-  - python setup.py -q install
-
-script:
-  - pytest --cov=./
+  - '3.6'
 
 branches:
   only:
   - master
 
-after_success:
-  - codecov || echo "codecov failed"
+install:
+  # code below is taken from http://conda.pydata.org/docs/travis.html
+  # We do this conditionally because it saves us some downloading if the
+  # version is the same.
+  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
+      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
+    else
+      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
+    fi
+  - bash miniconda.sh -b -p $HOME/miniconda
+  - export PATH="$HOME/miniconda/bin:$PATH"
+  - hash -r
+  - conda config --set always_yes yes --set changeps1 no
+  - conda update -q conda
+  # Useful for debugging any issues with conda
+  - conda info -a
+
+  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
+  - source activate test-environment
+  - pip install --only-binary=numpy,scipy,pandas numpy scipy pandas pytest pytest-cov codecov --quiet
+  # install TensorFlow (CPU version).
+  - pip install tensorflow==1.12.0 --quiet
+  # install PyTorch (CPU version).
+  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl --quiet
+  - python setup.py -q install
+
+script: pytest --cov=cornac
+
+after_success: codecov || echo "codecov failed"
+
+deploy:
+  provider: pypi
+  user: qttruong
+  password:
+    secure: OgWchiEQ9xaSRU9QL4agyfd3MOPqI0yu4SzR2k1htyPxf1mdTWY1Zrg3xNf0TkWmv27LYcJcmz0304iWvMP7WdrGAZs4pTvCHoNoIZhN4oOoZ0zOG3hJMXaCPSsBXgcB3Pn7RkfVRspHpophjCQSwBYyKkmKaCofba682quGUoqZ3xyNPwtzL2fbsLDAyPhwJJrz4mgdhsPH21b3i7oq2l8KfdfEk+lmB1lp0QxXl/xU8+0Ycm98+khRbpWjGyPBgocN82WQTrhuQaD+QBpADLvC8RG6+urjJDZO8bttVPnPRSIOkqK7K71OtF133oEmdwsyfm30FV5IfkeGk+jGCGTmeWG61nJ2zcgzebJvwZnnOGvAOG4tA/7t/Ut3+E9SLmFqvouufdhpCCWn4b4zY9VvdKwQdulM6w8095oQxRMLkFpy5UJZJuScboe7Iq+jj02oBfVJ182G685Skcuw2TWsEAjBJspNd7L7HeNwYH/T4bUUDKyGbX3RTra0C4udxFSbnZx950a6+ODCFQofeN84AYvI9m9FS7EKRZ7qhmu5yf+V0x3SrhT0hUZNcZZCEILM8y8xa8aHrBZRelWFTyAuD57vkiinu9TJ7vIacVS3tV4Ki6lpG2AGCP3yyoOYsHgyJJzXf/xkP6e9Dt5/Fn/EmZdr0NrLs9/Gv+xJ+6s=
+  distributions: "sdist bdist_wheel"
+  skip_existing: true
+  skip_cleanup: true
+  on:
+    tags: true
